b4rtaz/distributed-llama

.gitignore
Makefile
README.md
src/funcs.cpp

This PR adds a basic support for x86 AVX2 processor (Q40 x Q80 matmul).
```
@b4rtaz ➜ /workspaces/distributed-llama (feat/avx2) $ lscpu
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      48 bits physical, 48 bits virtual
CPU(s):                             8
On-line CPU(s) list:                0-7
Thread(s) per core:                 2
Core(s) per socket:                 4
Socket(s):                          1
NUMA node(s):                       1
Vendor ID:                          AuthenticAMD
CPU family:                         25
Model:                              1
Model name:                         AMD EPYC 7763 64-Core Processor
Stepping: …
```

feat: avx2

---

converter/convert-llama.py
docs/LLAMA.md

The previous implementation of the llama converter has set always `max_seq_len: 2048`. Llama 3 has a longer context than Llama 2, so now it's required to update `params.json` file manually before the conversion. Unfortunetly Llama repositorium doesn't have this parameter defined in the default configuration.

fix: convert-llama.py supports different max_seq_len.

---

src/funcs.cpp

Hi @b4rtaz
I managed to get a significant speed up on my machine with the following changes
I added AVX2 instructions to speed up the matmulQ40 in funcs.cpp
From my initial testing it definitely appears to be faster
With 1 worker:
sudo nice -n -20 ./main inference --steps 20 --prompt "Hello World! " --model ~/Meta-Llama-3-8B-Instruct-Distributed/dllama_original_q40.bin --tokenizer ~/Meta-Llama-3-8B-Instruct-Distributed/dllama-llama3-tokenizer.t --weights-float-type q40 --buffer-float-type q80 --nthreads 8 --workers 192.168.1.3:9990 [sudo] password for azamorn:
Using AVX2 instructions💡 arch: llama2
💡 dim: 4096
💡 hiddenDim: 14336
💡 nLayers: 32
💡 nHeads: 32
💡 nKvHeads: 8
💡 vocabSize: 128256
💡 seqLen: 2048
💡 nSlices: 2
💡 ropeTheta: 500000.0
📄 bosId: 128000
📄 eosId: 128001
🕒 ropeCache: 16384 …

Use AVX2 to speedup matmulQ40

---

src/llama2-tasks.cpp
src/transformer.cpp
src/transformer.hpp

Transfer / token
Model: dllama_meta-llama-3-8b_q40.bin
Buffer: Q80
| Devices | 0.5.0 | PR | Percentage change |
|-|----|-----|-----|
| 2 devices | S 510 kB + R 442 kB = 952 kB | S 272 kB + R 272 kB = 544 kB | -42.8% |
| 4 devices | S 1887 kB + R 867 kB = 2754 kB | S 816 kB + R 816 kB = 816 kB | -40.7% |
🤯 🤯

feat: speed up synchronization of mlp.

---

src/apps/dllama-api/dllama-api.cpp
src/socket.cpp

Still very buggy, but now I'm able to connect to the `dllama-api` by using Anything LLM client.

fix: chunked stream, close stream without econnreset.

---

examples/chat-api-client.js
src/apps/dllama-api/dllama-api.cpp
src/apps/dllama-api/types.hpp

This PR introduces a simple cache in the api server. It speeds up the inference in a chat client like AnythingLLM by reusing already processed input tokens.
Also, this PR resolves the problem with added unwanted `<|eot_id|>` to the response.

feat: naive cache.

---

.github/workflows/main.yml
Makefile
converter/convert-tokenizer-hf.py
converter/convert-tokenizer-llama3.py
converter/tokenizer-writer.py
src/app.cpp
src/apps/dllama-api/dllama-api.cpp
src/apps/dllama/dllama.cpp
src/tokenizer-test.cpp
src/tokenizer.cpp
src/tokenizer.hpp

This PR extends the tokenizer file format. Now it's possible to add to the tokenzier file the chat configuration.
```
...
seqLen: 8192
💡 nSlices: 1
💡 ropeTheta: 500000.0
📄 chatTemplate[0]: 
📄 chatTemplate[1]: <|start_header_id|>
📄 chatTemplate[2]: <|end_header_id|>
📄 chatTemplate[3]: <|eot_id|>
📄 chatTemplate[4]: <|start_header_id|>assistant<|end_header_id|>
📄 bosId: 128000
📄 eosId: 128001
📄 chatEosId: 128009
🕒 ropeCache: 131072 kB
⏩ Loaded 6175568 kB
```

feat: add to tokenizer chat configuration.

---

src/app.cpp
src/app.hpp
src/apps/dllama/dllama.cpp
src/commands.cpp
src/transformer.cpp
src/transformer.hpp

This argument allows to reduce the context size and the KV cache size.
An example of usage:
```
./dllama chat --model ... --nthreads 8 --max-seq-len 1024
```

feat: --max-seq-len argument.

---

src/funcs.cpp

This PR fixes a bug in the `rms` function for processors with AVX2 instructions.

fix: rms avx2 bug.

---

Makefile
src/app.cpp
src/app.hpp
src/apps/dllama-api/dllama-api.cpp
src/apps/dllama/dllama.cpp
src/commands.cpp
src/funcs.cpp
src/quants.cpp
src/transformer.cpp

Hi! I've been using distributed-llama for a month or so on the 4x Raspberry Pi 5 cluster that I made, and I saw that dllama and dllama-api didn't have a --usage feature. I'd rather you be focused on meaningful changes to the codebase, so I thought I could help out on this more mundane task, making the tool extremely friendly with respect to usage. I also enhanced the Makefile with a few targets and made the default more meaningful ("make" alone now makes the three apps, instead of just "utils", and I added clean, all, apps, and tests targets).
Here's a pull request. Please let me know if I did anything wrong. :) And keep up the great work!
---
To dllama and dllama-api, I added three arguments that can pull up a usage description: -h, --help, or --usage . Furthermore, for dllama, you can …

Added help/usage to apps and new Makefile targets

---

src/app.cpp
src/nn/nn-network.cpp

This PR resolves an issue where inference would get stuck during long runs. I have tested it in a single run up to pos=5000 without any issues, and it should work for higher positions as well.

fix: fixed inference getting stuck

---

src/dllama-api.cpp

Change the `/v1/models` api endpoint to return the basename of the model path instead of the hardcoded value `"dl"`.
Successfully tested with [Open WebUI](https://docs.openwebui.com/). Makes identifying the current model in use a little easier.
This works, but my C++ knowledge is a little limited. So this can be taken as a more detailed feature request instead :)

dllama-api: /v1/models: return basename of the model

---

converter/convert-tokenizer-hf.py

The converter-tokenizer-hf is now aware of byte characters (such as `"<0x0A>"` and parses them correctly as the actual character (such as a newline `"\n"`.
This is useful for mistral, tinyllama, and others using the same tokenizing method. 
See https://github.com/ggml-org/llama.cpp/issues/4622 for more context.
Fix #188.

fix: converter hf now handles byte characters. Closes #188

---

src/nn/vulkan/matmul-forward-q80-q40-f32.comp

Tested on Macbook Pro M1.
Previous (~80ms / token).
```
🔶 Pred   78 ms Sync    0 ms | Sent     0 kB Recv     0 kB |  Tensor
🔶 Pred   87 ms Sync    0 ms | Sent     0 kB Recv     0 kB |  parallel
🔶 Pred   83 ms Sync    0 ms | Sent     0 kB Recv     0 kB | ism
🔶 Pred   88 ms Sync    0 ms | Sent     0 kB Recv     0 kB | ,
🔶 Pred   93 ms Sync    0 ms | Sent     0 kB Recv     0 kB |  a
🔶 Pred   94 ms Sync    0 ms | Sent     0 kB Recv     0 kB |  technique
```
Now (~66ms / token):
```
🔶 Pred   67 ms Sync    0 ms | Sent     0 kB Recv     0 kB | This
🔶 Pred   66 ms Sync    0 ms | Sent     0 kB Recv     0 kB |  note
🔶 Pred   66 ms Sync    0 ms | Sent     0 kB Recv     0 kB |  is
🔶 Pred   66 ms Sync    0 ms | Sent     0 kB Recv     0 kB |  a
🔶 Pred   66 ms Sync    0 ms | Sent     0 kB Recv     0 kB …
```

feat: vulkan matmul optimization.

---

src/nn/nn-vulkan.cpp

This version fixes the selection of memory type in Vulkan, significantly improving inference speed on NVIDIA GPUs.
With this, it's now possible to run Distributed Llama on two GPUs within the same machine, for example. Check [this test](https://github.com/b4rtaz/distributed-llama/discussions/194).

fix: vulkan memory type.

---

src/nn/nn-vulkan-test.cpp
src/nn/nn-vulkan.cpp
src/nn/vulkan/matmul-forward-q80-q40-f32.comp

The Vulkan matmul shader (`matmul-forward-q80-q40-f32.comp`) was optimized.
Tested on NVIDIA Tesla T4 16 GB using the `llama3_1_8b_instruct_q40` model with `--buffer-float-type q80`.
Before:
```
🔶 Pred  151 ms Sync    0 ms | Sent     0 kB Recv     0 kB | )
🔶 Pred  151 ms Sync    0 ms | Sent     0 kB Recv     0 kB |  to
🔶 Pred  153 ms Sync    0 ms | Sent     0 kB Recv     0 kB |  be
```
This PR:
```
🔶 Pred   97 ms Sync    0 ms | Sent     0 kB Recv     0 kB |  obtained
🔶 Pred   96 ms Sync    0 ms | Sent     0 kB Recv     0 kB |  by
🔶 Pred   96 ms Sync    0 ms | Sent     0 kB Recv     0 kB |  pert
```

feat: vulkan tiled matmul

---

src/nn/nn-cpu-ops.cpp

fixes #219 
the (index + 1)th item is right past the last item copied, so equal here should be tolerated

fix: bad bound check in shiftForward_F32_F32

---

src/dllama-api.cpp

The EOS detector caches data inside it. Not resetting it may result in the remains of the last response appearing at the start of the next response.

fix: reset EOS detector across requests

---

src/nn/nn-vulkan.cpp
src/nn/nn-vulkan.hpp

This PR reduces the number of bytes required for synchronization between the CPU and GPU in prediction mode.
Tested on NVIDIA GeForce RTX 3060 12GB (with `--steps 128`):
| Model | Tokens/s (previous version) | Tokens/s (this PR) |
| --- | --- | --- |
| `lama3_1_8b_instruct_q40` | 13.68 (73.07 ms/tok) | 14.83 (67.42 ms/tok) |
| `qwen3_0.6b_q40` | 44.41 (22.52 ms/tok) | 61.98 (16.13 ms/tok) |

feat: reduce gpu sync size.

---

Makefile
src/nn/nn-vulkan-test.cpp
src/nn/nn-vulkan.cpp
src/nn/vulkan/cast-forward-f32-f32.comp
src/nn/vulkan/cast-forward-f32-q80.comp
src/nn/vulkan/embedding-forward-f32-f32.comp
src/nn/vulkan/matmul-forward-q80-q40-f32.comp
src/nn/vulkan/merge-add-forward-q80-f32.comp
src/nn/vulkan/mul-forward-f32-f32.comp
src/nn/vulkan/rms-norm-forward-f32-f32-f32.comp
src/nn/vulkan/shift-forward-f32-f32.comp
src/nn/vulkan/silu-forward-f32-f32.comp

```
🌋 Device: NVIDIA GeForce RTX 3060 Ti
🌋 DeviceApiVersion: 1.3.242
🌋 MaxComputeSharedMemory: 48 kB
🌋 NonCoherentAtomSize: 64 bytes
🌋 Heap[0]: 8192 MB
🌋 Heap[2]: 246 MB
```
| Model | Tokens/s (version 0.15.0) | Tokens/s (version 0.15.2) | Tokens/s (This PR) |
| --- | --- | --- | --- |
| `lama3_1_8b_instruct_q40` | 13.46 | 15.96  | 17.91  |
```
🌋 Device: NVIDIA GeForce RTX 3090
🌋 DeviceApiVersion: 1.4.303
🌋 MaxComputeSharedMemory: 48 kB
🌋 NonCoherentAtomSize: 64 bytes
🌋 Heap[0]: 24576 MB
🌋 Heap[2]: 246 MB
```
| Model | Tokens/s (version 0.15.0) | Tokens/s (version 0.15.2) | Tokens/s (This PR) |
| --- | --- | --- | --- |
| `llama3_3_70b_instruct_q40` | - | 4.22  | 4.35 |

feat: vulkan optimizations.

---

src/nn/vulkan/matmul-forward-q80-q40-f32.comp

This PR fixes a precision issue in multiplication for Qwen models on NVIDIA GPUs.
Tested on NVIDIA GeForce RTX 3060 12GB.
```
🌋 Device: NVIDIA GeForce RTX 3060                                                                                                                
🌋 DeviceApiVersion: 1.4.303                                                                                                                      
🌋 MaxComputeSharedMemory: 48 kB                                                                                                                  
🌋 NonCoherentAtomSize: 64 bytes                                                                                                                  
🌋 Heap[0]: 12288 MB …
```

fix: vulkan matmul q80 q40 f32 precision.
